version: '3.8'

services:
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./Website
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  tools:
    build: 
      dockerfile: Dockerfile
      context: ./Backend/Tools
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: mysql:5.7
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./Database:/docker-entrypoint-initdb.d